name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v4
        with:
          install: true

      - name: Install dependencies
        run: uv sync

      - name: Validate shloka files
        run: uv run python -m cli validate

      - name: Build static site
        run: uv run python -m cli build

      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: 'arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-for-subhashitani'
          aws-region: us-east-1

      - name: Deploy to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync --delete build/ s3://subhashitani.tanay.tech/